[package]
name = "parawasm"
version = "0.1.0"
edition = "2018"
default-run = "test"

[[bin]]
name = "test"
path = "main.rs"

[dependencies]
anyhow = "1.0.41"
symbolic-demangle = "8.3.1"
wasmer = { version = "2.0.0", features = ["singlepass"] }

[profile.release]
debug = true
